// sw.js (auto-generated by Workbox)
importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.5.4/workbox-sw.js');

workbox.core.clientsClaim();
workbox.core.skipWaiting();

// Precache manifest injected at build time
workbox.precaching.precacheAndRoute(self.__WB_MANIFEST);

// Runtime caching
workbox.routing.registerRoute(
  ({ request }) => request.mode === 'navigate',
  new workbox.strategies.NetworkFirst({
    cacheName: 'pages-cache',
  })
);

workbox.routing.registerRoute(
  ({ request }) =>
    ['style', 'script', 'image', 'font'].includes(request.destination),
  new workbox.strategies.StaleWhileRevalidate({
    cacheName: 'static-resources',
  })
);
// sw.js
importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.5.4/workbox-sw.js');

workbox.core.clientsClaim();
workbox.core.skipWaiting();

// Precache manifest injected at build time
workbox.precaching.precacheAndRoute(self.__WB_MANIFEST);

// Cache the files-list.json
workbox.routing.registerRoute(
  ({url}) => url.pathname.endsWith('files-list.json'),
  new workbox.strategies.NetworkFirst({
    cacheName: 'files-list-cache',
  })
);

